version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: webapp
      MONGO_INITDB_ROOT_PASSWORD: MyDataAcc3ss#
      MONGO_INITDB_DATABASE: notification-app
    ports:
      - "27017:27017"
    networks:
      - application-demo
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - application-demo

networks:
  application-demo:
    driver: bridge

volumes:
  mongo_data:

