spring.application.name: notification-demo

spring:
  data:
    mongodb:
      uri: "mongodb://webapp:MyDataAcc3ss#@localhost:27017/admin"
      database: "notification-app"

notifications-app:
  users.default-users:
    SPORTS:
      - id: someId
        name: username
        email: mail@mail.com
        phone: 1234567890
        subscriptionList:
          - SPORTS
          - MOVIES
        channels:
          - EMAIL